setwd("C:/WORK/EGI/data")
ams_all_rev = read.table("ams_all_rev.csv",header=T, sep=",")  
apj_all_rev = read.table("apj_all_rev.csv",header=T, sep=",")  
AMS_rev_BU_CUST = read.table("AMS_rev_BU_CUST.csv",header=T, sep=",")  
APJ_rev_BU_CUST = read.table("APJ_rev_BU_CUST.csv",header=T, sep=",")  
AMS_rev_prod_ln = read.table("AMS_rev_prod_ln.csv",header=T, sep=",")  
APJ_rev_prod_ln = read.table("APJ_rev_prod_ln.csv",header=T, sep=",")  
