SELECT
    SEC_NON_SEC_POSN_CURR_QTR,
    SEC_NON_SEC_POSN_CURR_MTH,
    SEC_NON_SEC_POSN_PRCS_DT,
    SUM(SEC_NON_SEC_POSN_NET_USD_AM) AS SEC_NET_USD_AM,
    SUM(CP_SEC_POSN_NET_USD_AM)      AS CP_SEC_NET_USD_AM
FROM
    EGI.SRC_IC_SEC_NON_SEC_POSN_AMS_F
GROUP BY
    SEC_NON_SEC_POSN_CURR_QTR,
    SEC_NON_SEC_POSN_CURR_MTH,
    SEC_NON_SEC_POSN_PRCS_DT
ORDER BY
    SEC_NON_SEC_POSN_CURR_QTR,
    SEC_NON_SEC_POSN_CURR_MTH,
    SEC_NON_SEC_POSN_PRCS_DT;