select distinct SHIP_ID,SHIP_LN_ITM_ID,SHIP_DT,SHIP_SRC_SYS_KY,SHPT_CUST_ID,SHPT_ISO_CTRY_CD,B.CUST_ID,B.GEO_CD,C.GEO_NM,C.CTRY_NM,C.RGN_NM,C.CTRY_CD 
from EGI.RZ_SEC_NON_SEC_POSN_AMS_F A 
JOIN EGI.RZ_CUST_HIER_D B ON A.SHPT_CUST_ID=B.CUST_ID
JOIN EGI.RZ_GEO_D C ON B.GEO_CD=C.GEO_CD; 